import React from 'react';
import Head from 'next/head';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + '-Jari' : 'Jari Africa'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="Ecommerce" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          Header
        </header>

        <main>
          {children}
        </main>

        <footer>
          Footer
        </footer>
      </div>
    </>
  );
}
